/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7d3fbd6d0f310701764b584a2ba411b4)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	ACCESS_AUTHORIZATION_URL: string;
	ACCESS_CLIENT_ID: string;
	ACCESS_CLIENT_SECRET: string;
	ACCESS_ISSUER: string;
	ACCESS_JWKS_URL: string;
	ACCESS_TOKEN_URL: string;
	ANIME_LIST_MCP_TOKEN: string;
	CALORIE_MCP_TOKEN: string;
	COOKIE_ENCRYPTION_KEY: string;
	OWNER_EMAIL: string;
	READER_MCP_TOKEN: string;
	SETLINE_MCP_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker-entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_AUTHORIZATION_URL" | "ACCESS_CLIENT_ID" | "ACCESS_CLIENT_SECRET" | "ACCESS_ISSUER" | "ACCESS_JWKS_URL" | "ACCESS_TOKEN_URL" | "ANIME_LIST_MCP_TOKEN" | "CALORIE_MCP_TOKEN" | "COOKIE_ENCRYPTION_KEY" | "OWNER_EMAIL" | "READER_MCP_TOKEN" | "SETLINE_MCP_TOKEN">> {}
}
