/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7026f9e2a0aaba55dd9f30762e42bef1)
interface __BaseEnv_Env {
	ANIME_LIST_MCP_TOKEN: string;
	CALORIE_MCP_TOKEN: string;
	READER_MCP_TOKEN: string;
	SETLINE_MCP_TOKEN: string;
	AUTH0_ISSUER: string;
	AUTH0_OWNER_USER_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker-entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ANIME_LIST_MCP_TOKEN" | "CALORIE_MCP_TOKEN" | "READER_MCP_TOKEN" | "SETLINE_MCP_TOKEN" | "AUTH0_ISSUER" | "AUTH0_OWNER_USER_ID">> {}
}
