/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3cb1fbb1b1fe7eb30eef298ed79098d1)
interface __BaseEnv_Env {
	SETLINE_MCP_TOKEN: string;
	AUTH0_ISSUER: string;
	AUTH0_OWNER_USER_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker-entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SETLINE_MCP_TOKEN" | "AUTH0_ISSUER" | "AUTH0_OWNER_USER_ID">> {}
}
