import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const packageRoot = resolve(new URL('..', import.meta.url).pathname);
const sourcePath = resolve(packageRoot, '../../ops/config/projects.json');
const outputPath = resolve(packageRoot, 'src/catalog.ts');
const source = JSON.parse(await readFile(sourcePath, 'utf8'));
const projects = source.projects
  .filter(
    (project) =>
      project.lifecycle === 'maintained' &&
      project.public?.listing === 'maintained' &&
      project.domains?.[0]
  )
  .map((project) => ({
    id: project.id,
    name: project.public?.name ?? project.name,
    url: `https://${project.domains[0]}`,
    description: project.public?.description,
    tier: project.tier,
    priority: project.portfolio?.priority,
    category: project.public?.category,
    maturity: project.public?.maturity,
    spotlight: project.public?.spotlight,
    pillarId: project.public?.pillarId,
    domains: project.domains,
  }));

const serialized = JSON.stringify(projects, null, 2)
  .replace(/"([a-z]+)":/g, '$1:')
  .replace(/: "([^"]*)"/g, ": '$1'")
  .replace(/(\n {4}url: '[^']*')\n/g, '$1,\n')
  .replace(/\n {2}}\n/g, '\n  },\n');
const content = `// Generated by scripts/generate-catalog.mjs. Do not edit by hand.\nimport type { PortfolioProject } from './types';\n\nexport const DEFAULT_PROJECTS: readonly PortfolioProject[] = ${serialized};\n`;
await writeFile(outputPath, content);
console.log(`Generated ${projects.length} projects from ${sourcePath}`);
