import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MonitoringProvider } from './monitoring-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
  preload: false,
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  display: 'swap',
  preload: false,
});

export const metadata: Metadata = {
  metadataBase: new URL('https://domains.sassmaker.com'),
  title: 'drank · Track Domain Ratings in Your Browser',
  description:
    'A High Signal research tool for tracking the authority score of popular sites and your own — entirely in your browser, with no sign-up or server storage.',
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: 'any' },
    ],
    apple: '/apple-touch-icon.png',
  },
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'drank · Track Domain Ratings in Your Browser',
    description:
      'A High Signal research tool for domain authority. No account, no server — everything lives in this tab.',
    url: 'https://domains.sassmaker.com',
    type: 'website',
    images: [{ url: '/globe.svg', alt: 'drank domain rating tracker' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'drank · Track Domain Ratings in Your Browser',
    description:
      'A High Signal research tool for domain authority. No account, no server — everything lives in this tab.',
    images: ['/globe.svg'],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <head>
        {/* fleet-jsonld:start (generated by apply-agent-surfaces; edit registry, not this) */}
        <script
          type="application/ld+json"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: fleet-generated JSON-LD
          dangerouslySetInnerHTML={{
            __html: `{"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://sassmaker.com/#org","name":"SaaS Maker (Foundry)","url":"https://sassmaker.com","sameAs":["https://sassmaker.com","https://github.com/High-Signal-App/drank"]},{"@type":"SoftwareApplication","@id":"https://domains.sassmaker.com/#app","name":"DRank","url":"https://domains.sassmaker.com","description":"Ahrefs Domain Rating tracker feeding High Signal /domains and fleet domain marketing work.","publisher":{"@id":"https://sassmaker.com/#org"}}]}`,
          }}
        />
        {/* fleet-jsonld:end */}
      </head>
      <body className="min-h-full flex flex-col" style={{ contain: 'layout' }}>
        {/* LCP shell: fixed overlay so it never participates in document flow.
            Removing it on hydration causes zero layout shift. */}
        <div
          id="drank-lcp-shell"
          className="fixed inset-0 z-40 bg-zinc-950 text-zinc-200"
          aria-hidden="true"
        >
          <div className="mx-auto max-w-7xl px-6 pt-10 pb-6">
            <div className="text-6xl font-semibold tracking-[-3.2px] text-white">
              Track Domain Ratings.
              <br />
              100% in your browser.
            </div>
          </div>
        </div>
        <MonitoringProvider>{children}</MonitoringProvider>
      </body>
    </html>
  );
}
