import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
} from 'node:fs';
import { basename, extname, join, relative, resolve, sep } from 'node:path';

export const CATALOG_SCHEMA_VERSION = 1;
export const CAPABILITY_TYPES = Object.freeze([
  'skill',
  'script',
  'template',
  'doc',
]);

export const ERROR_CODES = Object.freeze({
  usage: 'ERR_USAGE',
  unknownCommand: 'ERR_UNKNOWN_COMMAND',
  notFound: 'ERR_NOT_FOUND',
  invalidType: 'ERR_INVALID_TYPE',
  catalogInvalid: 'ERR_CATALOG_INVALID',
  internal: 'ERR_INTERNAL',
});

const ROOT_DEFINITIONS = Object.freeze([
  {
    type: 'skill',
    relativePath: 'skills',
    include: (path) => basename(path) === 'SKILL.md',
  },
  {
    type: 'skill',
    relativePath: 'teammates/skills',
    include: (path) => basename(path) === 'SKILL.md',
  },
  {
    type: 'script',
    relativePath: 'scripts',
    include: isOperatorScript,
  },
  {
    type: 'template',
    relativePath: 'templates',
    include: () => true,
  },
  {
    type: 'doc',
    relativePath: 'docs',
    include: (path) => extname(path).toLowerCase() === '.md',
    excludeDirectories: new Set(['archive']),
  },
]);

function isOperatorScript(path) {
  const name = basename(path);
  if (name.includes('.test.')) return false;
  const extension = extname(name).toLowerCase();
  return ['', '.js', '.mjs', '.py', '.sh'].includes(extension);
}

function isGeneratedDoc(path, content) {
  const filename = basename(path).toLowerCase();
  const preamble = content.slice(0, 1_200);
  return (
    /(?:^|[-_.])(latest|report)(?:[-_.]|$)/.test(filename)
    || /\bgenerated\b.{0,80}\bby\b/i.test(preamble)
    || /do not edit by hand/i.test(preamble)
    || /autogenerated|auto-generated/i.test(preamble)
  );
}

function toPosix(path) {
  return path.split(sep).join('/');
}

function cleanScalar(value = '') {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"'))
    || (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1).trim();
  }
  return trimmed;
}

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
  if (!match) return {};

  const metadata = {};
  const lines = match[1].split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const field = line.match(/^([a-zA-Z][\w-]*):\s*(.+)$/);
    if (!field) continue;
    if (field[2] === '>' || field[2] === '|') {
      const parts = [];
      while (lines[index + 1]?.match(/^\s+\S/)) {
        parts.push(lines[index + 1].trim());
        index += 1;
      }
      metadata[field[1]] = parts.join(field[2] === '>' ? ' ' : '\n');
    } else {
      metadata[field[1]] = cleanScalar(field[2]);
    }
  }
  return metadata;
}

function withoutFrontmatter(content) {
  return content.replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/, '');
}

function firstHeading(content) {
  return withoutFrontmatter(content).match(/^#{1,3}\s+(.+?)\s*$/m)?.[1]?.trim();
}

function firstParagraph(content) {
  const blocks = withoutFrontmatter(content).split(/\r?\n\s*\r?\n/);
  for (const block of blocks) {
    const lines = block
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);
    if (
      lines.length === 0
      || lines[0].startsWith('#')
      || lines[0].startsWith('```')
      || lines[0].startsWith('|')
      || lines.every((line) => /^[-*]\s/.test(line))
    ) {
      continue;
    }
    return lines
      .join(' ')
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      .replace(/[`*_]/g, '')
      .slice(0, 280)
      .trim();
  }
  return '';
}

function firstScriptComment(content) {
  for (const line of content.split(/\r?\n/).slice(0, 30)) {
    const comment = line.match(/^\s*(?:#|\/\/)\s+(.+?)\s*$/)?.[1];
    if (
      comment
      && !comment.startsWith('!')
      && !comment.startsWith('shellcheck')
      && !comment.startsWith('eslint')
    ) {
      return comment.slice(0, 280);
    }
  }
  return '';
}

function titleFromPath(path) {
  const filename = basename(path);
  const extension = extname(filename);
  const stem = extension ? filename.slice(0, -extension.length) : filename;
  return stem
    .replace(/[-_.]+/g, ' ')
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

function slug(value) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9._/-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^[-/]+|[-/]+$/g, '');
}

function relativeSlug(path, rootPath) {
  const relativePath = toPosix(relative(rootPath, path));
  const extension = extname(relativePath);
  const stem = extension
    ? relativePath.slice(0, -extension.length)
    : relativePath;
  return slug(stem);
}

function walkFiles(rootPath, excludeDirectories = new Set()) {
  const files = [];
  const entries = readdirSync(rootPath, { withFileTypes: true })
    .sort((left, right) => left.name.localeCompare(right.name));

  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;
    const path = join(rootPath, entry.name);
    if (entry.isDirectory()) {
      if (!excludeDirectories.has(entry.name)) {
        files.push(...walkFiles(path, excludeDirectories));
      }
    } else if (entry.isFile()) {
      files.push(path);
    }
  }
  return files;
}

function createItem({ type, filePath, sourceRoot, opsRoot, content }) {
  const metadata = type === 'skill' ? parseFrontmatter(content) : {};
  const path = toPosix(relative(resolve(opsRoot, '../..'), filePath));
  const pathSlug = relativeSlug(filePath, sourceRoot);
  const skillName = metadata.name || basename(resolve(filePath, '..'));
  const name = type === 'skill'
    ? skillName
    : type === 'script'
      ? titleFromPath(filePath)
      : firstHeading(content) || titleFromPath(filePath);
  const summary = type === 'skill'
    ? metadata.description || firstParagraph(content) || `Fleet skill: ${name}.`
    : type === 'script'
      ? firstScriptComment(content) || `Fleet operator script: ${name}.`
      : firstParagraph(content) || `Fleet ${type}: ${name}.`;
  const identifierSlug = type === 'skill' ? slug(skillName) : pathSlug;
  const item = {
    id: `${type}:${identifierSlug}`,
    type,
    name,
    summary,
    path,
  };

  Object.defineProperty(item, '_searchText', {
    value: normalizeText(`${item.id} ${type} ${name} ${summary} ${path} ${content.slice(0, 12_000)}`),
    enumerable: false,
  });
  return item;
}

export function buildCatalog(opsRoot = resolve(import.meta.dirname, '..')) {
  const resolvedOpsRoot = resolve(opsRoot);
  const items = [];
  const issues = [];
  const roots = [];

  for (const definition of ROOT_DEFINITIONS) {
    const sourceRoot = join(resolvedOpsRoot, definition.relativePath);
    roots.push({
      type: definition.type,
      path: toPosix(relative(resolve(resolvedOpsRoot, '../..'), sourceRoot)),
      exists: existsSync(sourceRoot),
    });

    if (!existsSync(sourceRoot)) {
      issues.push({
        level: 'error',
        code: 'MISSING_ROOT',
        message: `Missing ${definition.type} catalog root: ${definition.relativePath}`,
        path: definition.relativePath,
      });
      continue;
    }

    for (const filePath of walkFiles(sourceRoot, definition.excludeDirectories)) {
      if (!definition.include(filePath)) continue;
      try {
        const content = readFileSync(filePath, 'utf8');
        if (definition.type === 'doc' && isGeneratedDoc(filePath, content)) continue;
        items.push(createItem({
          type: definition.type,
          filePath,
          sourceRoot,
          opsRoot: resolvedOpsRoot,
          content,
        }));
      } catch (error) {
        issues.push({
          level: 'error',
          code: 'UNREADABLE_FILE',
          message: `Could not read ${toPosix(relative(resolvedOpsRoot, filePath))}: ${error.message}`,
          path: toPosix(relative(resolve(resolvedOpsRoot, '../..'), filePath)),
        });
      }
    }
  }

  items.sort((left, right) => left.id.localeCompare(right.id));
  return {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    generatedFrom: 'foundry/ops',
    opsRoot: resolvedOpsRoot,
    roots,
    items,
    issues,
  };
}

export function publicItem(item) {
  return {
    id: item.id,
    type: item.type,
    name: item.name,
    summary: item.summary,
    path: item.path,
  };
}

export function listCapabilities(catalog, { type } = {}) {
  return catalog.items
    .filter((item) => !type || item.type === type)
    .map(publicItem);
}

export function normalizeText(value = '') {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9._/-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function scoreItem(item, query, tokens) {
  const normalizedId = normalizeText(item.id);
  const normalizedName = normalizeText(item.name);
  const phraseQuery = query.replace(/[-_./]+/g, ' ');
  const phraseName = normalizedName.replace(/[-_./]+/g, ' ');
  const normalizedSummary = normalizeText(item.summary);
  const normalizedPath = normalizeText(item.path);
  const searchable = item._searchText
    || normalizeText(`${item.id} ${item.name} ${item.summary} ${item.path}`);

  if (!tokens.every((token) => searchable.includes(token))) return 0;

  let score = 1;
  if (normalizedId === query) score += 1_000;
  if (phraseName === phraseQuery) score += 900;
  if (normalizedId.startsWith(query)) score += 350;
  if (phraseName.startsWith(phraseQuery)) score += 300;
  if (normalizedId.includes(query)) score += 220;
  if (phraseName.includes(phraseQuery)) score += 180;

  for (const token of tokens) {
    if (normalizedId.split(/[:/._-]/).includes(token)) score += 100;
    if (phraseName.split(' ').includes(token)) score += 80;
    if (normalizedSummary.includes(token)) score += 30;
    if (normalizedPath.includes(token)) score += 20;
    if (item.type === token) score += 10;
  }
  return score;
}

export function searchCapabilities(catalog, query, { type, limit = 20 } = {}) {
  const normalizedQuery = normalizeText(query);
  const tokens = normalizedQuery.split(' ').filter(Boolean);
  if (tokens.length === 0) return [];

  return catalog.items
    .filter((item) => !type || item.type === type)
    .map((item) => ({ item, score: scoreItem(item, normalizedQuery, tokens) }))
    .filter((result) => result.score > 0)
    .sort((left, right) => (
      right.score - left.score || left.item.id.localeCompare(right.item.id)
    ))
    .slice(0, limit)
    .map(({ item, score }) => ({ ...publicItem(item), score }));
}

export function getCapability(catalog, id) {
  const item = catalog.items.find((candidate) => candidate.id === id);
  return item ? publicItem(item) : null;
}

export function generateContext(catalog, { query, type, dense = false } = {}) {
  const items = query
    ? searchCapabilities(catalog, query, { type, limit: Number.POSITIVE_INFINITY })
    : listCapabilities(catalog, { type });

  if (dense) {
    return items
      .map((item) => `${item.id}\t${item.name}\t${item.summary}`)
      .join('\n');
  }

  const lines = [
    '# Fleet capability context',
    '',
    'Discover canonical Fleet Ops tools with:',
    '',
    '```bash',
    'node foundry/ops/scripts/fleet-capabilities.mjs search "<intent>" --dense',
    'node foundry/ops/scripts/fleet-capabilities.mjs get "<capability-id>"',
    '```',
    '',
    'Read a capability at its repository path before using it. Discovery is read-only.',
  ];

  for (const capabilityType of CAPABILITY_TYPES) {
    const matching = items.filter((item) => item.type === capabilityType);
    if (matching.length === 0) continue;
    lines.push('', `## ${capabilityType[0].toUpperCase()}${capabilityType.slice(1)}s`, '');
    for (const item of matching) {
      lines.push(`- \`${item.id}\` — ${item.summary} (\`${item.path}\`)`);
    }
  }
  return lines.join('\n');
}

export function diagnoseCatalog(catalog) {
  const issues = [...catalog.issues];
  const seen = new Set();
  const idPattern = /^(skill|script|template|doc):[a-z0-9][a-z0-9._/-]*$/;

  for (const item of catalog.items) {
    if (seen.has(item.id)) {
      issues.push({
        level: 'error',
        code: 'DUPLICATE_ID',
        message: `Duplicate capability identifier: ${item.id}`,
        path: item.path,
      });
    }
    seen.add(item.id);

    for (const field of ['id', 'type', 'name', 'summary', 'path']) {
      if (typeof item[field] !== 'string' || item[field].trim() === '') {
        issues.push({
          level: 'error',
          code: 'MISSING_METADATA',
          message: `${item.id || item.path || 'Capability'} is missing ${field}`,
          path: item.path,
        });
      }
    }

    if (item.id && !idPattern.test(item.id)) {
      issues.push({
        level: 'error',
        code: 'INVALID_ID',
        message: `Invalid capability identifier: ${item.id}`,
        path: item.path,
      });
    }

    const absolutePath = resolve(catalog.opsRoot, '../..', item.path);
    if (!existsSync(absolutePath) || !statSync(absolutePath).isFile()) {
      issues.push({
        level: 'error',
        code: 'MISSING_FILE',
        message: `Capability path does not exist: ${item.path}`,
        path: item.path,
      });
    }
  }

  const errorCount = issues.filter((issue) => issue.level === 'error').length;
  const warningCount = issues.filter((issue) => issue.level === 'warning').length;
  return {
    healthy: errorCount === 0,
    counts: {
      items: catalog.items.length,
      roots: catalog.roots.length,
      errors: errorCount,
      warnings: warningCount,
    },
    roots: catalog.roots,
    issues,
  };
}

export function successEnvelope(command, data, meta = {}) {
  return {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    ok: true,
    command,
    data,
    meta,
  };
}

export function errorEnvelope(command, code, message, suggestions = [], meta = {}) {
  return {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    ok: false,
    command,
    error: {
      code,
      message,
      suggestions,
    },
    meta,
  };
}
