import type { Metadata } from 'next';
import './globals.css';
import { MonitoringProvider } from './monitoring-provider';

export const metadata: Metadata = {
  metadataBase: new URL('https://domains.sassmaker.com'),
  title: 'drank · Track Domain Ratings in Your Browser',
  description:
    'A High Signal research tool for tracking the authority score of popular sites and your own — entirely in your browser, with no sign-up or server storage.',
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: 'any' },
    ],
    apple: '/apple-touch-icon.png',
  },
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'drank · Track Domain Ratings in Your Browser',
    description:
      'A High Signal research tool for domain authority. No account, no server — everything lives in this tab.',
    url: 'https://domains.sassmaker.com',
    type: 'website',
    images: [{ url: '/globe.svg', alt: 'drank domain rating tracker' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'drank · Track Domain Ratings in Your Browser',
    description:
      'A High Signal research tool for domain authority. No account, no server — everything lives in this tab.',
    images: ['/globe.svg'],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        {/* fleet-jsonld:start (generated by apply-agent-surfaces; edit registry, not this) */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: `{"@context":"https://schema.org","@graph":[{"@type":"Person","@id":"https://sarthakagrawal.dev/#person","name":"Sarthak Agrawal","jobTitle":"AI Infrastructure & Product Engineer","url":"https://sarthakagrawal.dev","image":"https://avatars.githubusercontent.com/u/43884471?v=4","sameAs":["https://sarthakagrawal.dev","https://www.linkedin.com/in/sarthakagrawal927","https://github.com/sarthakagrawal927","https://x.com/sarthakcodes","https://huggingface.co/sarthakagrawal927"],"knowsAbout":["AI infrastructure","Local-first software","Post-training language models","AI code review","Cloudflare Workers","TypeScript","Rust"],"affiliation":{"@type":"Organization","@id":"https://sassmaker.com/#app","name":"SaaS Maker","url":"https://sassmaker.com"}},{"@type":"WebSite","@id":"https://domains.sassmaker.com/#app","name":"Drank","url":"https://domains.sassmaker.com","description":"Ahrefs Domain Rating tracker feeding High Signal /domains and fleet domain marketing work.","publisher":{"@id":"https://sarthakagrawal.dev/#person"},"sameAs":["https://github.com/sass-maker"]}]}`,
          }}
        />
        {/* fleet-jsonld:end */}
      </head>
      <body className="min-h-full flex flex-col" style={{ contain: 'layout' }}>
        {/* LCP shell: fixed overlay so it never participates in document flow.
            Removing it on hydration causes zero layout shift. */}
        <div
          id="drank-lcp-shell"
          className="fixed inset-0 z-40 bg-zinc-950 text-zinc-200"
          aria-hidden="true"
        >
          <div className="mx-auto max-w-7xl px-6 pt-10 pb-6">
            <div className="text-[clamp(1.75rem,8.2vw,3.75rem)] leading-[1.05] font-semibold tracking-[-0.04em] text-white sm:leading-none sm:tracking-[-3.2px]">
              Track Domain Ratings.
              <br />
              100% in your browser.
            </div>
          </div>
        </div>
        <MonitoringProvider>{children}</MonitoringProvider>
      </body>
    </html>
  );
}
