// Generated by scripts/generate-catalog.mjs. Do not edit by hand.
import type { PortfolioProject } from './types';

export const DEFAULT_PROJECTS: readonly PortfolioProject[] = [
  {
    id: 'codevetter',
    name: 'CodeVetter',
    url: 'https://codevetter.com',
    description: 'AI code review platform — desktop-first, works offline.',
    tier: 'focus',
    category: 'product',
    maturity: 'public-ready',
    spotlight: true,
    "pillarId": 'build',
    domains: [
      "codevetter.com"
    ]
  },
  {
    id: 'pace',
    name: 'HeyPace',
    url: 'https://heypace.app',
    description: 'Local-only macOS voice agent that can understand what is on your screen.',
    tier: 'focus',
    category: 'product',
    maturity: 'public-ready',
    spotlight: true,
    "pillarId": 'build',
    domains: [
      "heypace.app"
    ]
  },
  {
    id: 'posttrainllm',
    name: 'PostTrainLLM',
    url: 'https://posttrainllm.com',
    description: 'A local factory for training, evaluating, and running specialist language models.',
    tier: 'focus',
    category: 'product',
    maturity: 'public-ready',
    spotlight: true,
    "pillarId": 'build',
    domains: [
      "posttrainllm.com"
    ]
  },
  {
    id: 'fleet-workspace',
    name: 'SaaS Maker',
    url: 'https://sassmaker.com',
    description: 'Software as a specialized service: a living studio of focused products built for particular problems and maintained in public.',
    tier: 'active',
    category: 'product',
    maturity: 'public-ready',
    spotlight: false,
    "pillarId": 'build',
    domains: [
      "sassmaker.com",
      "fleet.sassmaker.com"
    ]
  },
  {
    id: 'drank',
    name: 'Drank',
    url: 'https://domains.sassmaker.com',
    description: 'Domain Rating intelligence for product, SEO, and market research.',
    tier: 'active',
    category: 'helper',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'market',
    domains: [
      "domains.sassmaker.com"
    ]
  },
  {
    id: 'email-manager',
    name: 'Email Manager',
    url: 'https://mail.significanthobbies.com',
    description: 'A private Gmail workspace for local semantic search, sender insights, and explicit unsubscribe workflows.',
    tier: 'active',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "mail.significanthobbies.com"
    ]
  },
  {
    id: 'chatgpt-memory-insights',
    name: 'Memory Map',
    url: 'https://chatgpt.significanthobbies.com',
    description: 'Turn a ChatGPT export into a private, browser-computed map of recurring themes, facts, and conversations.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "chatgpt.significanthobbies.com"
    ]
  },
  {
    id: 'free-ai',
    name: 'Free AI',
    url: 'https://ai-gateway.sassmaker.com',
    description: 'OpenAI-compatible gateway across free-tier model providers.',
    tier: 'active',
    category: 'product',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'build',
    domains: [
      "ai-gateway.sassmaker.com"
    ]
  },
  {
    id: 'psi-swarm',
    name: 'PSI Swarm',
    url: 'https://performance.sassmaker.com',
    description: 'Repeated Lighthouse distributions for honest website performance tracking.',
    tier: 'active',
    category: 'helper',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'visibility',
    domains: [
      "performance.sassmaker.com"
    ]
  },
  {
    id: 'high-signal',
    name: 'High Signal',
    url: 'https://highsignal.app',
    description: 'Evidence-backed daily intelligence across technology, startups, finance, and public markets.',
    tier: 'active',
    category: 'product',
    maturity: 'public-ready',
    spotlight: true,
    "pillarId": 'learn',
    domains: [
      "highsignal.app"
    ]
  },
  {
    id: 'research-papers',
    name: 'Research Papers',
    url: 'https://papers.highsignal.app',
    description: 'Academic paper discovery and a structured research data asset.',
    tier: 'secondary',
    category: 'product',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "papers.highsignal.app"
    ]
  },
  {
    id: 'knowledge-base',
    name: 'Knowledge Base',
    url: 'https://knowledgebase.sassmaker.com',
    description: 'Private agent search over specialized corpora with ranked citations, provenance, and schema-aware retrieval.',
    tier: 'active',
    category: 'product',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'build',
    domains: [
      "knowledgebase.sassmaker.com",
      "search.sassmaker.com"
    ]
  },
  {
    id: 'significanthobbies',
    name: 'Significant Hobbies',
    url: 'https://significanthobbies.com',
    description: 'Plan meaningful hobbies, side quests, rituals, and life journeys.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'public-ready',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "significanthobbies.com"
    ]
  },
  {
    id: 'anime-list',
    name: 'Anime List',
    url: 'https://anime.significanthobbies.com',
    description: 'Anime and manga discovery with multi-axis filtering and personal watchlists.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "anime.significanthobbies.com"
    ]
  },
  {
    id: 'chess',
    name: 'Chess Coach',
    url: 'https://chess.significanthobbies.com',
    description: 'Browser chess against Stockfish with optional AI move coaching.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "chess.significanthobbies.com"
    ]
  },
  {
    id: 'looptv',
    name: 'LoopTV',
    url: 'https://tv.significanthobbies.com',
    description: 'A lean-back, TV-style random video player for curated channels.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "tv.significanthobbies.com"
    ]
  },
  {
    id: 'reader',
    name: 'Reader',
    url: 'https://read.significanthobbies.com',
    description: 'Capture, annotate, revisit, and discuss saved reading.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "read.significanthobbies.com"
    ]
  },
  {
    id: 'swe-interview-prep',
    name: 'SWE Interview Prep',
    url: 'https://learn.significanthobbies.com',
    description: 'A learning OS for software-engineering interview practice.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "learn.significanthobbies.com"
    ]
  },
  {
    id: 'calorie',
    name: 'Calorie',
    url: 'https://calorie.significanthobbies.com',
    description: 'A private, local-first food, water, and weight journal with transparent timing guidance.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "calorie.significanthobbies.com"
    ]
  },
  {
    id: 'setline',
    name: 'Setline',
    url: 'https://setline.significanthobbies.com',
    description: 'A mobile-first workout execution tracker for following user-authored plans, recording sets, and timing rest offline.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "setline.significanthobbies.com"
    ]
  },
  {
    id: 'rolepatch',
    name: 'RolePatch',
    url: 'https://rolepatch.com',
    description: 'AI-assisted resume tailoring, role research, and interview preparation.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'build',
    domains: [
      "rolepatch.com"
    ]
  },
  {
    id: 'karte',
    name: 'Karte',
    url: 'https://karte.cc',
    description: 'An AI link-in-bio that turns a profile into a conversation.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'public-ready',
    spotlight: false,
    "pillarId": 'build',
    domains: [
      "karte.cc"
    ]
  },
  {
    id: 'starboard',
    name: 'Starboard',
    url: 'https://starboard.codevetter.com',
    description: 'Organize and semantically search your GitHub stars.',
    tier: 'secondary',
    category: 'product',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "starboard.codevetter.com"
    ]
  },
  {
    id: 'app-health',
    name: 'App Health',
    url: 'https://health.sassmaker.com',
    description: 'Privacy-first endpoint health for Node, Go, and OpenTelemetry services.',
    tier: 'active',
    category: 'product',
    maturity: 'public-ready',
    spotlight: false,
    "pillarId": 'visibility',
    domains: [
      "health.sassmaker.com",
      "ingest.sassmaker.com"
    ]
  },
  {
    id: 'motion',
    name: 'Motion',
    url: 'https://motion.significanthobbies.com',
    description: 'Use your body as the controller for an iPhone-hosted game that can mirror to a larger screen.',
    tier: 'active',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'build',
    domains: [
      "motion.significanthobbies.com"
    ]
  },
  {
    id: 'what-it-takes-to-win',
    name: 'What It Takes to Win',
    url: 'https://paths.significanthobbies.com',
    description: 'Explore 2,585 documented early-breakthrough paths without pretending success follows a formula.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'learn',
    domains: [
      "paths.significanthobbies.com"
    ]
  },
  {
    id: 'sarthakagrawal-personal',
    name: 'Sarthak Agrawal',
    url: 'https://sarthakagrawal.dev',
    description: 'Personal portfolio of Sarthak Agrawal — AI infrastructure and product engineer.',
    tier: 'secondary',
    category: 'personal',
    maturity: 'maintained',
    spotlight: false,
    "pillarId": 'personal',
    domains: [
      "sarthakagrawal.dev"
    ]
  },
];
