name: Feedback Package CI

on:
  push:
    branches: [main]
    paths:
      - "foundry/packages/feedback/**"
      - ".github/workflows/feedback-package-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "foundry/packages/feedback/**"
      - ".github/workflows/feedback-package-ci.yml"
  workflow_dispatch:


concurrency:
  group: feedback-package-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  reusable:
    uses: sass-maker/workflows/.github/workflows/feedback-package-ci.yml@main
