name: Fleet Contracts CI

on:
  push:
    branches: [main]
    paths:
      - "package.json"
      - "foundry/ops/automation/**"
      - "foundry/ops/config/**"
      - "foundry/ops/host/**"
      - "foundry/ops/lib/**"
      - "foundry/ops/scripts/**"
      - "foundry/ops/templates/**"
      - "foundry/ops/test/**"
      - "foundry/ops/workflows"
      - "foundry/apps/public/public-directory/**"
      - ".gitmodules"
      - ".github/workflows/fleet-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "package.json"
      - "foundry/ops/automation/**"
      - "foundry/ops/config/**"
      - "foundry/ops/host/**"
      - "foundry/ops/lib/**"
      - "foundry/ops/scripts/**"
      - "foundry/ops/templates/**"
      - "foundry/ops/test/**"
      - "foundry/ops/workflows"
      - "foundry/apps/public/public-directory/**"
      - ".gitmodules"
      - ".github/workflows/fleet-ci.yml"
  workflow_dispatch:


concurrency:
  group: fleet-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  reusable:
    uses: sass-maker/workflows/.github/workflows/fleet-ci.yml@main
