name: Site Health CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: dashboard-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    uses: sass-maker/saas-maker/.github/workflows/site-health-ci.yml@4d9183a86f76e740e51d06c96299dbfc4f7d62d8
