name: Site Health CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: dashboard-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    uses: sass-maker/saas-maker/.github/workflows/site-health-ci.yml@8a8cf63ccf234e8194f1d4c7d29971ef19cfe674
