name: Test Reusable 6

on:
  workflow_dispatch:

concurrency:
  group: test-reusable-6
  cancel-in-progress: true

jobs:
  reusable:
    uses: sass-maker/workflows/.github/workflows/workflow-policy-ci.yml@main
