name: Update Global DR History

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  reusable:
    uses: sass-maker/workflows/.github/workflows/update-global-dr.yml@main
